name: Build and Publish Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.REGISTRY_PAT }}
    
    - name: Build the Docker image and tag it with todays date, also as latest build
      run: |
        docker build . --tag ghcr.io/se-ws22-ihnn/ihnn-api:latest
        docker push ghcr.io/se-ws22-ihnn/ihnn-api:latest
